/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import model.pegawai;

/**
 *
 * @author Hewlett-Packard
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    Connection koneksi;
    pegawai mPegawai;
    DateFormat date;

    public laporan() {
        mPegawai = new pegawai();

        date = new SimpleDateFormat("yyyy-MM-dd");
        this.date = DateFormat.getDateInstance();
        initComponents();
    }

    public Date getTanggal() {
        Date tanggal = (calendar.getDate());
        return tanggal;
    }

    public Date getTanggalAwal() {
        Date tanggal = (calendar1.getDate());
        return tanggal;
    }

    public Date getTanggalAkhir() {
        Date tanggal = (calendar2.getDate());
        return tanggal;
    }
    
    public String getNama(){
        return nama.getText();
    }
    
    public String getJabatan(){
        return jabatan.getText();
    }

    public void bulan(ActionListener a) {
        bulan.addActionListener(a);
    }

    public void range(ActionListener a) {
        range.addActionListener(a);
    }

    public void laporanListener(ActionListener a) {
        laporan.addActionListener(a);
    }
    
    public void exportListener (ActionListener a){
        export.addActionListener(a);
    }
 
    public void export2Listener (ActionListener a){
        export2.addActionListener(a);
    }
    
    public void pendataanListener(ActionListener a){
        pendataan.addActionListener(a);
    }

    public void keluarListener(ActionListener a){
        keluar.addActionListener(a);
    }
    
    public JButton bulanButton() {
        return bulan;
    }

    public JButton rangeButton() {
        return range;
    }

    public JButton pendataan() {
        return pendataan;
    }

    public JButton laporan() {
        return laporan;
    }
    
    public JButton export(){
        return export;
    }
    public JButton export2(){
        return export2;
    }

    public JLabel nama() {
        return nama;
    }

    public JLabel getNIP() {
        return nip;
    }

    public JLabel jabatan() {
        return jabatan;
    }

    public JLabel getPangkat() {
        return pangkat;
    }

    public void tabeljurnal(DefaultTableModel t) {
        jurnal.setModel(t);
    }

    public void setNama(String a) {
        this.nama.setText(a);
    }

    public void setNIP(String a) {
        this.nip.setText(a);
    }

    public void setJabatan(String a) {
        this.jabatan.setText(a);
    }

    public void setPangkat(String a) {
        this.pangkat.setText(a);
    }
  
    public void setGol(String a) {
        this.golruang.setText(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendataan = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jurnal = new javax.swing.JTable();
        export = new javax.swing.JButton();
        range = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        calendar = new org.jdesktop.swingx.JXDatePicker();
        bulan = new javax.swing.JButton();
        calendar1 = new org.jdesktop.swingx.JXDatePicker();
        calendar2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nip = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pangkat = new javax.swing.JLabel();
        golruang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        export2 = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendataan.setText("Pendataan");
        getContentPane().add(pendataan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        laporan.setText("Laporan");
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jurnal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Nama", "Kegiatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jurnal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 530, 160));

        export.setText("export ke excel");
        getContentPane().add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, 20));

        range.setText("cari");
        getContentPane().add(range, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel2.setText("Cari berdasarkan rentang waktu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        calendar.setBackground(new java.awt.Color(255, 75, 109));
        calendar.setForeground(new java.awt.Color(255, 255, 255));
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });
        getContentPane().add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, -1));

        bulan.setText("cari");
        getContentPane().add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        calendar1.setBackground(new java.awt.Color(255, 75, 109));
        calendar1.setForeground(new java.awt.Color(255, 255, 255));
        calendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendar1ActionPerformed(evt);
            }
        });
        getContentPane().add(calendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 160, -1));

        calendar2.setBackground(new java.awt.Color(255, 75, 109));
        calendar2.setForeground(new java.awt.Color(255, 255, 255));
        calendar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendar2ActionPerformed(evt);
            }
        });
        getContentPane().add(calendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 160, -1));

        jLabel3.setText("Tanggal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setText("Tanggal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel5.setText("NIP:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 160, 20));

        jLabel8.setText("Nama:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 20));

        jLabel6.setText("Jabatan:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 380, 20));

        jLabel9.setText("Pangkat:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(pangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 20));
        getContentPane().add(golruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, 20));

        jLabel7.setText("Cari berdasarkan bulan:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        export2.setText("export ke excel");
        getContentPane().add(export2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        keluar.setText("keluar");
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarActionPerformed

    private void calendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendar1ActionPerformed

    private void calendar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bulan;
    private org.jdesktop.swingx.JXDatePicker calendar;
    private org.jdesktop.swingx.JXDatePicker calendar1;
    private org.jdesktop.swingx.JXDatePicker calendar2;
    private javax.swing.JButton export;
    private javax.swing.JButton export2;
    private javax.swing.JLabel golruang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jabatan;
    private javax.swing.JTable jurnal;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nip;
    private javax.swing.JLabel pangkat;
    private javax.swing.JButton pendataan;
    private javax.swing.JButton range;
    // End of variables declaration//GEN-END:variables
}
