/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import model.pegawai;

/**
 *
 * @author Dheta
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    pegawai mPegawai;
    Connection koneksi;
    String [][] namakombo;
    public login() {
        mPegawai=new pegawai();
        username=new JComboBox();
        namakombo=mPegawai.getNamaLogin();
        initComponents();
    }
    
    
      public void setNama(String namakombo[][]) {
        this.namakombo=namakombo;
        username.setModel(new DefaultComboBoxModel<>(namakombo[1]));

    }

    public String getNama() {
        int indeks = username.getSelectedIndex();
        System.out.println("lllll" + indeks);
        System.out.println("panjangnya" + namakombo[0].length);
        
        return namakombo[1][indeks];
    }
    
    
    public void loginListener(ActionListener a){
        masuk.addActionListener(a);
    }
    
    public String nip(){
        return nip.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masuk = new javax.swing.JButton();
        nip = new javax.swing.JPasswordField();
        username = new javax.swing.JComboBox(namakombo[1]);
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 750));
        setPreferredSize(new java.awt.Dimension(870, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masuk.setBackground(new java.awt.Color(255, 153, 153));
        masuk.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        masuk.setText("Masuk");
        getContentPane().add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 433, 120, 40));

        nip.setBorder(null);
        nip.setOpaque(false);
        getContentPane().add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 260, 30));

        username.setBackground(new java.awt.Color(51, 153, 0));
        username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 102));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 280, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/PKL/login.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed

    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton masuk;
    private javax.swing.JPasswordField nip;
    private javax.swing.JComboBox<String> username;
    // End of variables declaration//GEN-END:variables
}
