/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Dheta
 */
public class tambahjurnal extends javax.swing.JFrame {

    /**
     * Creates new form tambahjurnal
     */
    public tambahjurnal() {
        initComponents();
    }

    public void setTanggal() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localdate = LocalDate.now();
        String tglDaftar = dtf.format(localdate);
        System.out.println(tglDaftar+"ini tanggalnya");
        tanggal.setText(tglDaftar);
    }

    public String getTanggal() {
        return tanggal.getText();
    }

    public String getKegiatan() {
        return kegiatan.getText();
    }

    public String nip() {
        return nip.getText();
    }

    public void setNama(String a) {
        this.nama.setText(a);
    }

    public void setNIP(String a) {
        this.nip.setText(a);
    }

    public void setJabatan(String a) {
        this.jabatan.setText(a);
    }

    public void setPangkat(String a) {
        this.pangkat.setText(a);
    }

    public void tambahListener(ActionListener a) {
        tambah.addActionListener(a);
    }
    
    public void kembaliListener(ActionListener a){
        kembali.addActionListener(a);
    }
    
    public JButton pendataan(){
        return pendataan;
    }
    
    public JButton laporan(){
        return laporan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kegiatan = new javax.swing.JTextField();
        tanggal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nip = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pangkat = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        pendataan = new javax.swing.JButton();
        laporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(kegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 260, 130));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, 20));

        jLabel2.setText("Kegiatan:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel3.setText("Tanggal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel8.setText("Nama:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, 20));

        jLabel5.setText("NIP:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        getContentPane().add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, 20));

        jLabel6.setText("Jabatan:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, 20));

        jLabel7.setText("Pangkat:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(pangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 160, 20));

        tambah.setText("simpan");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        kembali.setText("kembali");
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        pendataan.setText("pendataan");
        getContentPane().add(pendataan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        laporan.setText("laporan");
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahjurnal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jabatan;
    private javax.swing.JTextField kegiatan;
    private javax.swing.JButton kembali;
    private javax.swing.JButton laporan;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nip;
    private javax.swing.JLabel pangkat;
    private javax.swing.JButton pendataan;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
