/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.pegawai;

/**
 *
 * @author Dheta
 */
public class tambahjurnal extends javax.swing.JFrame {

    /**
     * Creates new form tambahjurnal
     */
    DateFormat date;
    pegawai mPegawai;
    String mKeterangan[][];
    String mObyek[][];

    public tambahjurnal() {
        mPegawai = new pegawai();
        keterangan = new JComboBox();
        obyek = new JComboBox();
        mObyek = mPegawai.getObyekPajak();
        mKeterangan = mPegawai.getKeterangan();
        initComponents();
    }

    public void setTanggal(String tanggall) {
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//        LocalDate localdate = LocalDate.now();
//        String tglDaftar = dtf.format(localdate);
//        System.out.println(tglDaftar + "ini tanggalnya");
//        tanggal.setText(tglDaftar);
        this.tanggal.setText(tanggall);
    }

    public void setObyek(String mObyek[][]) {
        this.mObyek = mObyek;
        obyek.setModel(new DefaultComboBoxModel<>(mObyek[1]));
    }

    public String getObyek() {
        int indeks = obyek.getSelectedIndex();
        System.out.println("lllll" + indeks);
        System.out.println("panjangnya" + mObyek[0].length);

        return mObyek[0][indeks];
    }

    public void setKet(String mKeterangan[][]) {
        this.mKeterangan = mKeterangan;
        keterangan.setModel(new DefaultComboBoxModel<>(mKeterangan[1]));
    }

    public void ketbaru(String a) {
        keterangan.setSelectedItem(a);
    }
    
    public void obbaru(String a) {
        obyek.setSelectedItem(a);
    }

    public String getKet() {
        int indeks = keterangan.getSelectedIndex();
        System.out.println("lllll" + indeks);
        System.out.println("panjangnya" + mKeterangan[0].length);

        return mKeterangan[0][indeks];
    }

    public String getTanggal() {
        return tanggal.getText();
    }

    public String getKegiatan() {
        return kegiatan.getText();
    }

    public String getNamanya() {
        return nama.getText();
    }

    public String getLokasi() {
        return lokasi.getText();
    }

    public void tambahListener(ActionListener a) {
        tambah.addActionListener(a);
    }

    public void tabeljurnal(DefaultTableModel t) {
        jurnal.setModel(t);
    }

    public void kembaliListener(ActionListener a) {
        kembali.addActionListener(a);
    }
    
    public void selesaiListener(ActionListener a){
        selesai.addActionListener(a);
    }

    public void submitListener(ActionListener a) {
        submit.addActionListener(a);
    }

    public void addKeterangan(ActionListener a) {
        addKet.addActionListener(a);
    }

    public void addObPajak(ActionListener a) {
        addObyek.addActionListener(a);
    }

    public JButton pendataan() {
        return pendataan;
    }

    public JButton laporan() {
        return laporan;
    }
    
    public JButton tambahket(){
        return addKet;
    }
    
    public JButton tambahobpajak(){
        return addObyek;
    }

    public JTextField lokasi1() {
        return lokasi;
    }

    public JTextField nama() {
        return nama;
    }

    public JButton add() {
        return submit;
    }

    public JComboBox obyek() {
        return obyek;
    }

    public JTextArea kegkeg(){
        return kegiatan;
    }
    
    public void keg(String lala) {
        this.kegiatan.setText(lala);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        pendataan = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        keterangan = new javax.swing.JComboBox(mKeterangan[1]);
        obyek = new javax.swing.JComboBox(mObyek[1]);
        lokasi = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kegiatan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jurnal = new javax.swing.JTable();
        submit = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        addObyek = new javax.swing.JButton();
        addKet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 20));

        jLabel2.setText("Kegiatan:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jLabel3.setText("Keterangan:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        tambah.setText("simpan");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        kembali.setText("kembali");
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        pendataan.setText("pendataan");
        getContentPane().add(pendataan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        laporan.setText("laporan");
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel4.setText("Tanggal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setText("Nama Wajib Pajak/Obyek Pajak:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel10.setText("Obyek Pajak:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        keterangan.setBackground(new java.awt.Color(51, 153, 0));
        keterangan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        keterangan.setForeground(new java.awt.Color(255, 255, 102));
        keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keteranganActionPerformed(evt);
            }
        });
        getContentPane().add(keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, 20));

        obyek.setBackground(new java.awt.Color(51, 153, 0));
        obyek.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        obyek.setForeground(new java.awt.Color(255, 255, 102));
        obyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obyekActionPerformed(evt);
            }
        });
        getContentPane().add(obyek, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 20));
        getContentPane().add(lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 280, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 240, -1));

        jLabel11.setText("Lokasi:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        kegiatan.setColumns(20);
        kegiatan.setRows(5);
        jScrollPane1.setViewportView(kegiatan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 280, 60));

        jurnal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Wajib Pajak", "Alamat", "Obyek Pajak", "Hasil Pendataan", "Keterangan"
            }
        ));
        jScrollPane2.setViewportView(jurnal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 480, 110));

        submit.setText("tambahkan");
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        selesai.setText("selesai");
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        addObyek.setText("+");
        getContentPane().add(addObyek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        addKet.setText("+");
        getContentPane().add(addKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keteranganActionPerformed

    }//GEN-LAST:event_keteranganActionPerformed

    private void obyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obyekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obyekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahjurnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahjurnal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addKet;
    private javax.swing.JButton addObyek;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jurnal;
    private javax.swing.JTextArea kegiatan;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> keterangan;
    private javax.swing.JButton laporan;
    private javax.swing.JTextField lokasi;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> obyek;
    private javax.swing.JButton pendataan;
    private javax.swing.JButton selesai;
    private javax.swing.JButton submit;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
